### ISSUE TITLE
Getting a bug when I have this plugin activated. 

### ISSUE THREAD

**Issue by agirlcreative** [jeremyrwross/advanced-custom-fields-image-size-select#1]
One, this plugin is great, thank you for the creation of it! I am having an issue what displays when I have debug on:

Notice: Trying to access array offset on value of type bool in /wp-content/plugins/acf-image-size-select/fields/class-acf-field-image-size-select.php on line 119

Notice: Trying to access array offset on value of type bool in /wp-content/plugins/acf-image-size-select/fields/class-acf-field-image-size-select.php on line 120

Notice: Trying to access array offset on value of type bool in /wp-content/plugins/acf-image-size-select/fields/class-acf-field-image-size-select.php on line 121

I tried deactivating my other stuff as well but this error persists and only goes away when I deactivate it itself...

**Comment by jeremyrwross** [comment]
Thanks for this report, I will look into it ASAP

**Comment by jeremyrwross** [comment]
Fixed in # https://github.com/jeremyrwross/advanced-custom-fields-image-size-select/releases/tag/v1.0.2 #
